version: '3.9'
services:
  db:
    image: postgres:12
    container_name: postgres-server
    networks:
      - todo-app-backend-network
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - todo-app-backend-network
    container_name: django_backend
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:

networks:
  todo-app-backend-network:
    name: django-todo-app-network